### ISSUE TITLE
You are a garbage person

### ISSUE THREAD

**Issue by yegors** [Kaliendo/Windscribe-generator#2]
You realize that you are taking away resources from people who actually need free accounts, because they can't afford to pay for a VPN?  We offer free service for people like that, not assholes who are too cheap to pay for stuff. 

Instead of working to improve the service, we're gonna have to work on CAPTCHAs to prevent assholes like you from abusing a goodwill service. You bring shame to your entire lineage.

**Comment by Kaliendo** [comment]
Lmao what's the difference between a software automating the creation of test accounts and someone doing it manually? you're still capped to 10GB so of you're "an asshole who is too cheap to pay for stuff" you will do the same thing with or without my software.

Also i don't think i'll shame anyone of my entire lineage because of this.

Yeah you can implement a captcha and make this worse to automate, i don't have exposed a vulerability, nor done anything drastically bad, i don't get why you're so upset and have to attack me personally.

**Comment by Kaliendo** [comment]
If you want to discuss about this leave me a way to contact you i don't like public shows

**Comment by httpjamesm** [comment]
You are a garbage person.
